### PR TITLE
Add opens attribute

### PR DESCRIPTION
**Pull request by sbleon**
Adds an `opens` attribute to control the direction the picker opens. Also specifies some package versions because the latest bootstrap-daterangepicker and moment don't work correctly with this directive.

### CODE REVIEW

**Comment by sbleon** [comment]
@luisfarzati can you explain why this PR was closed? Thanks!

**Comment by luisfarzati** [comment]
Honestly, I don't remember. But looking at the contents, I might be have closed it by error. Let me reopen it and let @timdockins or @alanjames1987 inspect this. Thank you!

**Comment by sbleon** [comment]
Thanks!

**Comment by alanjames1987** [comment]
It looks like most everything in this pull request is already in `master`. I will try to pull it in and see if there are major changes.

**Pull request merged**
